<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php echo $this->getLayout()->createBlock('airhotels/profilepage')->setTemplate('airhotels/profilepage.phtml')->toHtml(); 
	  echo $this->getLayout()->createBlock('airhotels/notifications')->setTemplate('airhotels/property/dashboard_notifications.phtml')->toHtml();
      echo $this->getLayout()->createBlock('airhotels/invitefriends')->setTemplate('airhotels/property/dashboard_invitefriends.phtml')->toHtml();
      echo $this->getLayout()->createBlock('airhotels/property_yourlist')->setTemplate('airhotels/property/dashboardinbox.phtml')->toHtml(); ?>
<div class="dashboard my_dashbd">   
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>

