<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>

<?php
/**
 * For hourly wise property
 * Get the Hourly Product Id
 */ 
$productId = Mage::getSingleton('core/session')->getHourlyProductId();
/**
 * Get the PropertyTime Value 
 */
$propertyTime = Mage::getModel('catalog/product')->load($productId)->getPropertyTime();
/**
 * get the property Time label id
 */
$propertyTimeData = Mage::helper('airhotels/airhotel')->getPropertyTimeLabelByOptionId();
?>

<?php

$_item = $this->getItem();
/**
 * Get the visible insite Visibility 
 */
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
    <td><?php
     /**
      * If product url goes to checkout with Product
      */
    if ($this->hasProductUrl()):?>
    <a href="<?php echo $this->getProductUrl() ?>" 
    title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image">
    <?php endif;?>
    <img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" 
    alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
    <?php if ($this->hasProductUrl()):?></a>
    <?php endif;?></td>
    <td width="50%">
        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>">
            <?php echo $this->htmlEscape($this->getProductName());
                  echo '<br>';
                  $subId = Mage::getSingleton('core/session')->getSubId();
                   $subscriptionValue = Mage::getSingleton('core/session')->getsubscriptionValue();
                  if($subId > 0){ echo $subscriptionValue; } 
             ?></a>
        <?php else: ?>
            <?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?>
        </h2>
        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
            <dd<?php if(count($_options)<= 2){?> style="width:49%" <?php } ?>
             <?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
             <?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">* 
            <?php echo $message['text'] ?></p>
        <?php endforeach; ?>
        <?php endif; ?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
    
     <?php 
     /**
      * For hourly based property
      */ 
     if($propertyTime == $propertyTimeData){
     /**
      * Get the Hourly Night Fee 
      */
     $hourlyNightFee = Mage::getSingleton('core/session')->getHourlyNightFee();  
     /**
      * Overall TOtal Hours 
      */     
     $overallTotalHours = Mage::getSingleton('core/session')->getOverallTotalHours();   
     ?>     
     <td class="a-center"><?php if(!empty($overallTotalHours)){ 
     echo $overallTotalHours; 
     } 
     /**
      *  Check with Hourly Night Free is not  an empty
      */
if(!(empty($hourlyNightFee)) && ($hourlyNightFee >= 1) ){
     echo ' <span class="excluding_hours">['.$this->__('Excluding night hour(s)').']</span>';    
     }
     ?></td> 
     <?php } ?>

    <?php if ($canApplyMsrp): ?>
        <td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link">
                <?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), 
                            "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
        </td>
    <?php else: ?>

        <?php
        /**
         * Get the Display Cart Price Value
         */ 
        if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-center"><?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                <?php endif; ?>
            </span>


            <?php if (Mage::helper('weee')->getApplied($_item)){ ?>

                <div id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;" class="cart-tax-info" >
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $getTax): ?>
                        <span class="weee">
                            <?php echo $getTax['title']; ?>: 
                            <?php echo Mage::helper('checkout')->formatPrice($getTax['amount'],true,true); ?>
                            </span>
                        <?php endforeach; ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $taxValue): ?>
                        <span class="weee">
                            <?php echo $taxValue['title']; ?>:
                             <?php echo Mage::helper('checkout')->formatPrice($taxValue['amount_incl_tax'],true,true); ?>
                             </span>
                        <?php endforeach; ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $taxVal): ?> 
                        <span class="weee">
                           <?php echo $taxVal['title']; ?>: 
                            <?php echo Mage::helper('checkout')->formatPrice($taxVal['amount_incl_tax'],true,true); ?>
                            </span>
                        <?php endforeach; ?>
                    <?php } ?>
                </div>

                <?php
                /**
                 * Get the Type of Dispaly Value
                 */ 
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee">
                        <?php echo Mage::helper('weee')->__('Total'); ?>: 
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                        </span>
                    </div>
                <?php endif; ?>
            <?php } ?>
        </td>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span  onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

            </span>
            <?php
            /**
             * GetApplied Value For all Properties
             */ 
            if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: 
                            <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?>
                            </span><?php endforeach; ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?><span class="weee">
                        <?php echo $tax['title']; ?>: 
                            <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $taxArr): ?><span class="weee">
                        <?php echo $taxArr['title']; ?>: 
                            <?php echo Mage::helper('checkout')->formatPrice($taxArr['amount_incl_tax'],true,true); ?>
                            </span>
                        <?php endforeach; ?>
                    <?php } ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: 
                        <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
    <?php endif; ?>
 
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total" >
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php else: ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php endif; ?>

        </span>

      
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
 <!-- Calculating the tax Value Starts -->
            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?><span class="weee">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?>
                        </span><?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="weee">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?>
                        </span>
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $taxValue): ?> 
                      <span class="weee">  <?php echo $taxValue['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($taxValue['row_amount_incl_tax'],true,true); ?>
                        </span><?php endforeach; ?>
                        <?php } ?></div>
                   <!-- Calculating the tax Value Ends -->     

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                     <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    
     <?php 
     /**
      * For hourly based property 
      */ 
     if(  ($propertyTime == $propertyTimeData) && !(empty($hourlyNightFee)) &&  ($hourlyNightFee >= 1) ) {
     $propertyOverNightFee = Mage::helper('airhotels/airhotel')->getPropertyOverNightFeeByProductId($productId);                    
     ?>
     <td class="a-center"><?php if(!empty($propertyOverNightFee)){ 
     echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol().$propertyOverNightFee; 
     } ?></td>
     <?php } ?>     
    
    <td class="a-center"><a href="<?php echo $this->getDeleteUrl()?>" 
    title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove2">
    <?php echo $this->__('Remove item')?></a></td>
    </tr>
