<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<?php $_item = $this->getItem() ?>
<tr>
    <td class="a-center"><a href="<?php echo $this->getItemDeleteUrl($_item) ?>" 
    title="<?php echo $this->__('Remove Item')?>" class="btn-remove2">
    <?php echo $this->__('Remove Item')?></a></td>
    <td><a href="<?php echo $this->getItemUrl($_item) ?>" 
    title="<?php echo $this->htmlEscape($this->getItemName($_item)) ?>" 
    class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($this->getItemProductForThumbnail($_item), 'thumbnail')->resize(75); ?>" width="75" 
    alt="<?php echo $this->htmlEscape($this->getItemName($_item)) ?>" /></a></td>
    <td>
        <h3 class="product-name"><a href="<?php echo $this->getItemUrl($_item) ?>">
        <?php echo $this->getItemName($_item) ?></a></h3>
        <?php echo $this->getItemDescription($_item) ?>
        <?php if($_item->getMessage()): ?>
            <p class="item-msg <?php if($_item->getHasError()): ?>error<?php else: ?>notice<?php endif; ?>">* 
            <?php echo $_item->getMessage() ?></p>
        <?php endif; ?>
    </td>
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td class="a-center">
        <input type="checkbox" value="1" name="cart[<?php echo $_item->getId() ?>][wishlist]" class="checkbox" />
    </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($_item)); ?>
    </td>
    <?php endif; ?>
    <td class="a-center">
        <input name="cart[<?php echo $_item->getId() ?>][qty]" 
        value="<?php echo $this->getItemQty($_item) ?>" size="4" class="input-text qty" maxlength="12" />
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($_item)); ?>
    </td>
    <?php endif; ?>
</tr>
