<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php if ($this->getQuote()->hasVirtualItems()): ?>
    <div class="col2-set">
        <h2 class="legend"><?php echo $this->__('Other Items in Your Order') ?></h2>
        <div class="col-1 col-narrow"></div>
        <div class="col-2 col-wide">
            <h3><?php echo $this->__('Items') ?> <span class="separator">|</span>
             <a href="<?php echo $this->getVirtualProductEditUrl() ?>">
             <?php echo $this->__('Edit Items') ?></a></h3>
            <table class="data-table" id="unavailable-shipping-table">
                <col />
                <col width="1" />
                <thead>
                    <tr>
                        <th><?php echo $this->__('Product Name') ?></th>
                        <th class="a-center"><?php echo $this->__('Qty') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
                    <tr>
                        <td><?php echo $this->getItemHtml($_item) ?></td>
                        <td class="a-center"><?php echo $_item->getQty() ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('unavailable-shipping-table')</script>
        </div>
    </div>
<?php endif; ?>
