<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<?php

$productId = Mage::getSingleton('core/session')->getHourlyProductId();
/**
 * For hourly wise property
 */  
$propertyTime = Mage::getModel('catalog/product')->load($productId)->getPropertyTime();
$propertyTimeData = Mage::helper('airhotels/airhotel')->getPropertyTimeLabelByOptionId(); 
$seats = (int) Mage::getSingleton('core/session')->getAccomodate();
?>

<div class="cart my-account">
    <div class="page-title">
        <h1><span style="float: left; display: block; line-height: 47px;"><?php echo $this->__('Shopping Cart') ?></span>
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types floatright">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        </h1>
        
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>">
                        <?php echo $this->helper('airhotels')->__('Image') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>">
                        <span class="nobr cartname"  style=""><?php echo $this->helper('airhotels')->__('Name') ?></span>
                        <span class="nobr ci cartin"   <?php if($seats <= 0){?> style="width:36%" <?php } ?>>
                        <?php echo $this->helper('airhotels')->__('Check In') ?></span>
                        <span class="nobr co cartout"  style=""><?php echo $this->helper('airhotels')->__('Check Out') ?></span>
                        <?php if($seats > 0){?>
                        <span class="nobr accom" style=""><?php echo $this->helper('airhotels')->__('Accomodate(s)') ?></span>
                        <?php } ?>
                        </th>                        
                        <?php if($propertyTime == $propertyTimeData){?>
                        <th class="a-center" colspan=" "><?php echo $this->helper('airhotels')->__('No. of hour(s)') ?></th>
                        <th class="a-center" colspan=" "><?php echo $this->helper('airhotels')->__('Price') ?><br />
                        <?php echo $this->__('(per hour)') ?></th>
                        <?php }else{ ?>
                        <th class="a-center" colspan=" "><?php echo $this->helper('airhotels')->__('Price') ?><br />
                        <?php $subId = Mage::getSingleton('core/session')->getSubId();
                        if($subId != 0){
                        ?>
                         <?php echo $this->__('(per Itearation)') ?></th> 
                        <?php  } else { ?>
                        <?php echo $this->__('(per night)') ?></th>    
                        <?php } 
}
                        ?> 
                        
                        
                         <?php 
                         /**
                          * For hourly based property
                          */ 
                         if($propertyTime == $propertyTimeData){    
                         $hourlyNightFee = Mage::getSingleton('core/session')->getHourlyNightFee();
                         if(!(empty($hourlyNightFee)) && ($hourlyNightFee >=1) ){
                         ?> 
                         <th class="a-center" colspan=" "><?php echo $this->helper('airhotels')->__('Overnight Fee') ?><br />
                         <?php echo $this->__('(per night)') ?></th>
                         <?php }
                          } ?>
                        
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center">Delete</th>
                    </tr>
                    
                </thead>
               
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
                <?php echo $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): 
                echo $this->getChildHtml('shipping'); 
                endif; ?>
            </div>
        </div>
        <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>
</div>
