<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$hostDetails 	= Mage::getSingleton('customer/session')->getCustomer();
$hostID 		= $hostDetails->getId();
$requestValue 	= $this->getRequest('');
$controllerVal 	= $requestValue->getActionName();
$id = $this->getRequest()->getParam('id');
?>
<div class="content_block">
	<h1 class="dashboard_leftside_heading"><?php echo $this->__('Profile Information'); ?></h1>
  	<div class="dashboard_leftside_heading_contents">
	    <ul>
		    <li><a href="<?php echo Mage::helper('airhotels/url')->getProfileUrl(); ?>" <?php if($controllerVal == 'profile' ){?>class="selected"<?php }?>><?php echo $this->__('Edit Profile'); ?></a></li>
		    <li><a href="<?php echo Mage::getBaseUrl().'property/property/uploadphoto/'; ?>" <?php if($controllerVal == 'uploadphoto'){?>class="selected"<?php }?>><?php echo $this->__('Photo, Video '); ?></a> </li>
		    <li><a href="<?php echo Mage::getBaseUrl().'property/multistep/verification/'; ?>" <?php if($controllerVal == 'verification' || $controllerVal == 'accountverification'){?>class="selected"<?php }?>><?php echo $this->__('Trust and Verification'); ?></a> </li>
		    <li><a href="<?php echo Mage::getBaseUrl().'property/dashboard/reviewpage/'; ?>" <?php if($controllerVal == 'reviewpage'){?>class="selected"<?php }?>><?php echo $this->__('Reviews'); ?></a></li>
	 	</ul>
  	</div>
  	<div class="clearfix invite_friends_button_section">
	    <ul>
	  		<li class="invite_friends_button"><a target="_blank" href="<?php echo $this->getBaseUrl()."airhotels/multistep/viewprofile/id/$hostID";?>"><?php echo $this->__('View Profile');?></a></li>
	  	</ul>
 	</div>
</div>