<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$requestParam 	= $this->getRequest('');
$controller 	= $requestParam->getActionName();
$id = $this->getRequest()->getParam('id');
?>
<div class="content_block">
	<h1 class="dashboard_leftside_heading"><?php echo $this->__('My Trips'); ?></h1>
	<div class="dashboard_leftside_heading_contents">
	  	<ul>
		    <li><a href="<?php echo Mage::getBaseUrl().'property/general/yourtrip/'; ?>" <?php if($controller == 'yourtrip'){?>class="selected"<?php }?>><?php echo $this->__('Upcoming Trips'); ?></a></li>
		    <li><a href="<?php echo Mage::getBaseUrl().'property/invitefriends/currenttrip/'; ?>" <?php if($controller == 'currenttrip'){?>class="selected"<?php }?>><?php echo $this->__('Current Trips'); ?></a></li>  
		    <li><a href="<?php echo Mage::getBaseUrl().'property/invitefriends/previoustrip/'; ?>" <?php if($controller == 'previoustrip'){?>class="selected"<?php }?>><?php echo $this->__('Previous Trips'); ?></a></li>
	  	</ul>
  	</div>
</div>