<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$request 			= $this->getRequest('');
$controllerAction 	= $request->getActionName();
$customerID 		= $this->getRequest()->getParam('id');
$customer = $address = Mage::getModel('customer/customer')->load($customerID);
$profilePhoto 		= Mage::getModel('airhotels/product')->getCustomerPictureById($customerID);
$customerName 		= $customer->getName();
$mobileVerificationCode = $profilePhoto[0]['mobile_verified_profile'];
$tagsId         	= Mage::getModel('airhotels/tagsverification')->getCollection()->getAllIds();

/**
 * To Display the customer profile image in myaccount
 *  Display customer profile information.
 */
?>
<div class="left_block">
	<div class="user_profile_img">
	  	<div class="userimgonly">
	    	<?php if(!empty($profilePhoto[0]["imagename"])){
	        	$imageURL = Mage::getBaseUrl('media') . "catalog/customer/" . $profilePhoto[0]["imagename"];
	             	echo "<img class='profilephoto' src='" . $imageURL . "' /> ";
				}else{
					echo "<img class='profilephoto' src='".$this->getSkinUrl('images/no_user.jpg')."' /> ";
				} ?>
		</div>
  	</div>
</div>
<div class="content_block">
	<div style="position: relative;">
		<h1 class="dashboard_leftside_heading"><?php echo $this->__('Verification'); ?></h1>
	  	<i class="airhotel-sprite question-circle dashnotify" data-content='Verifications help build trust between guests and hosts and can make property easier.' data-placement="bottom" <?php if(!Mage::helper('airhotels/mobile')->isMobile()) { ?>rel="popover"<?php } ?>></i>
  	</div>
  	<div class="dashboard_leftside_heading_contents">
  		<ul>
  			<li>
  				<i class='sprimg dashverified_icon'></i>
  				<span class='dashverified_label'><?php echo $this->__('Email Address Verified');?></span>
  			</li>
  			<?php foreach ($tagsId as $tagsId){
  				$verifiedTagVal = Mage::getModel ( 'airhotels/verifyhost' )->getCollection ()->addFieldToFilter('host_id',array('eq'=>$customerID))->addFieldToFilter('tag_id',array('in'=>$tagsId));
  				$tagName 		= Mage::getModel('airhotels/tagsverification')->load($tagsId)->getTagName();
  				if(count($verifiedTagVal) == 0) {
					echo "<li><i class='sprimg dash_notverified_icon'></i><span class='dashverified_label'>".ucfirst($tagName).$this->__(' Not Verified Yet')."</span></li>";
				} else {
					foreach(verifiedTagVal as $once) {
						$verifiedHostTag = $once->getHostTags();
						if($verifiedHostTag == 1) {
							echo "<li><i class='sprimg dashverified_icon'></i><span class='dashverified_label'>".ucfirst($tagName).$this->__(' Verified')."</span></li>";
						} else {
							echo "<li><i class='sprimg dash_notverified_icon'></i> <span class='dashverified_label'>".ucfirst($tagName).$this->__(' Not Verified Yet')."</span></li>";
						}
					}
				}
			}
			if($mobileVerificationCode == "verified") { ?>
    		<li>
    			<i class="sprimg dashverified_icon"></i>
    			<span class="dashverified_label"><?php echo $this->__("Phone Number Verified"); ?></span>
    		</li>
    		<?php } else { ?>
    		<li>
    			<i class="sprimg dash_notverified_icon"></i>
    			<span class="dashverified_label"><?php echo $this->__("Phone Not Verified Yet");?></span>
    		</li>
    		<?php } ?>
  		</ul>
  	</div>
</div>
<?php
$customerPhoto 		= Mage::getModel('airhotels/customerphoto')->load($customerID);
$hostSchool 	 = $customerPhoto->getSchool();
$hostWork 		 = $customerPhoto->getWork();
?>
<div>
  <div style="position: relative;"><h1 class="dashboard_leftside_heading"><?php echo $this->__('About Me'); ?></h1></div>
  <ul class="vp_aboutme_section clearfix">
  	<li><h4><?php echo $this->__('Education'); ?></h4><span><?php if(!empty($hostSchool)){ echo $hostSchool; }else{ echo "---"; }?></span></li>
  	<li><h4><?php echo $this->__('Work'); ?></h4><span><?php if(!empty($hostWork)){ echo $hostWork; }else{ echo "---"; }?></span></li>
  </ul>
</div>
<?php
$counter = 0;
$currencySymbol 	= Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
$totalproperties 	= Mage::getModel('catalog/product')->getCollection()
					->addFieldToFilter("userid",array("eq"=>$customerID))
					->addFieldToFilter(array(array('attribute' => 'status', 'eq' => '1')))
					->addFieldToFilter(array(array('attribute' => 'propertyapproved', 'eq' => '1')))
                    ->setOrder('created_at','DESC');
$listingCount 		= $totalproperties->count();

?>
<div class="content_block">
	<div style="position: relative;"><h1 class="dashboard_leftside_heading"><?php echo $this->__('Listings ('.$listingCount.')'); ?></h1></div>
  	<div class="vp_mylisting">
  		<ul id="results" class="results-container">
    	<?php
    	$count = 0;
    	foreach($totalproperties as $totalproperty) {
	    	$experienceId 		= $totalproperty['entity_id'];
	    	$_experience 		=  Mage::getModel('catalog/product')->load($experienceId);
	    	$productUrl 		= $_experience->getProductUrl();
	    	$experiencePrice 	= $currencySymbol . round(Mage::helper('directory')->currencyConvert($_experience->getPrice(), Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0);
		?>
		<li class="search-wrapper vp_listing" id="product_map_over_<?php echo  $_experience->getId();  ?>"  data-name="" data-src="" data-state="" currency-data="<?php echo $experiencePrice; ?>">
			<div class="search-result-container">
				<a class="search-result-pimage" href="<?php echo $productUrl; ?>" style="background: url(
							<?php
							if ($_experience->getImage() != 'no_selection') {
							echo Mage::getBaseUrl ( Mage_Core_Model_Store::URL_TYPE_MEDIA ).'catalog/product/'.$_experience->getImage();
							} else {
							echo $_experience->getImageUrl();
							}
							?>)
							">
				</a>
				<div class="search-result-right">
					<div class="search-result-title-left">
						<div class="room_details">
				              <div class="vp_ratings">
					               <?php
		                            $rating 		= Mage::getModel('airhotels/airhotels')->getCustomerRatings($_experience->getId());
		                            $avgRatingVal 	= $sum = 0;
		                            for ($i = 0; $i < count($rating); $i++) {
		                                $sum +=$rating[$i]["percent"];
		                            }
		                           	if(count($rating) != 0){
		                           		$avgRatingVal = $sum / count($rating);
		                           	}
		                           	$reviewBlockmethod = new Apptha_Airhotels_Block_Airhotels();
		                            if ($avgRatingVal > 1 && $avgRatingVal <= 20) {
		                                echo $reviewBlockmethod->showratingCode(1);
		                            } else if ($avgRatingVal > 21 && $avgRatingVal <= 40) {
		                                echo $reviewBlockmethod->showratingCode(2);
		                            } else if ($avgRatingVal > 41 && $avgRatingVal <= 60) {
		                                echo $reviewBlockmethod->showratingCode(3);
		                            } else if ($avgRatingVal > 61 && $avgRatingVal <= 80) {
		                                echo $reviewBlockmethod->showratingCode(4);
		                            } else if ($avgRatingVal > 81 && $avgRatingVal <= 100) {
		                                echo $reviewBlockmethod->showratingCode(5);
		                            } else {
		                                echo $reviewBlockmethod->showratingCode(0);
		                            }
		                            ?>
					                <div class="reviews-count"><?php
					                	$respondCollection 	= Mage::getModel('airhotels/customerphoto')->getCollection();
			                            $summaryData 		= Mage::getModel('review/review_summary')->load($_experience->getId());
			                            $respondArray 		= array();
										foreach ($respondCollection as $respondCollections){
											$respondArray[] = $respondCollections->getCustomerId();
										}
										if(in_array($_experience->getUserid(), $respondArray)){
			                            	foreach ($respondCollection as $respondCollections){
					                        	if($respondCollections->getCustomerId() == $_experience->getUserid()){ ?>
													<div class="respond-review">
														<span class="vp_countno"><?php
															if(count($summaryData->getReviewsCount()) != ''){
																echo $summaryData->getReviewsCount();
															}else{
																echo "0";
															}
															echo strtoupper($this->__(' Reviews'));?></span>
													</div><?php
												}
											}
										}?>
		                             </div>
	                         	</div>
	                         	<div class="search_price_right">
	                           		<span class="vp_price"> <?php echo $experiencePrice; ?></span>
	                        	</div>
							</div>
						</div>
					</div>
				</div>
			 	<div class="vp_listingsection">
			 		<h2><?php echo ucwords(Mage::helper('airhotels/property')->getPropertyName($_experience->getName()));?></h2>
	                <p class="vp_address">
	                <?php
	                if (strlen($_experience->getPropertyadd()) >= 50)
	                	echo ucwords(substr($_experience->getPropertyadd(), 0, 50)) . "...";
					else
	                	echo ucwords($_experience->getPropertyadd()); ?>
					</p>
				</div>
    		</li>
    	<?php
    	 $count++;
         if($count >= 5):
         break;
         endif;
        } ?>
  	</ul>
  </div>
</div>
