<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 
     /**
      * check weather thecheckout process is possible
      * If possible show the book it now submit button 
      * or otheriwise hide it 
      */
     if ($this->isPossibleOnepageCheckout() ):?>
    <button type="button" id="bookit_now_submit_button" title="<?php echo $this->__('Book it Now') ?>" 
    class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"
    <?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>
    onclick="bookitNowSubmitButtonAction(); window.location='<?php echo $this->getCheckoutUrl() ?>';">
    <?php echo $this->__('Book it Now') ?></button>

 <script type="text/javascript">
 var $jq = jQuery.noConflict();   
 function bookitNowSubmitButtonAction(){
 $jq('#bookit_now_submit_button').attr('disabled','disabled');
 }
 </script>
    
<?php endif?>
