<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<!-- login page  starts -->
<div class="col2-set">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-1">
        <h3>
         <!-- Check guest checkout is allowed -->
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
        <?php echo $this->__('Checkout as a Guest or Register') ?>
        <?php else: ?>
        <?php echo $this->__('Register to Create an Account') ?>
        <?php endif; ?></h3>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p>
            <?php echo $this->__('Register with us for future convenience:') ?>
            </p>
        <?php else: ?>
            <p>
            <strong>
            <?php echo $this->__('Register and save time!') ?>
            </strong>
            <br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li>
                <?php echo $this->__('Fast and easy check out') ?>
                </li>
                <li>
                <?php echo $this->__('Easy access to your booking history and status') ?>
                </li>
            </ul>
        <?php endif; ?>
        <!-- Check guest checkout is allowed or not -->
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                 <!-- Check guest checkout  -->
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <?php 
                /**
                 * Checking guest or not
                 */
                 ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                    <label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                    <label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
            </ul>
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul class="ul">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your booking history and status') ?></li>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
    </div>
    <!-- login form starts -->
    <div class="col-2">
        <h3><?php echo $this->__('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <h4><?php echo $this->__('Already registered?') ?></h4>
            <p><?php echo $this->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
    <!-- login form ends -->
</div>
<!-- login page  ends -->
<div class="col2-set">
<!--  Submit button starts -->
    <div class="col-1">
        <div class="buttons-set">
            <p class="required">&nbsp;</p>
            <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register'); ?></span></span></button>
        </div>
    </div>
<!--  Submit button ends -->    
    <!-- Forgot password satrts -->
    <div class="col-2">
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left">
            <?php echo $this->__('Forgot your password?') ?></a>
            <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
    </div>
    <!-- Forgot password ends -->
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) { loginForm.submit(); }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true; loginForm.submit();
        }
    }
//]]>
</script>
