<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="multiple-checkout">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Change Billing Address') ?></h1>
        <button type="button" title="<?php echo $this->__('Add New Address') ?>" 
        class="button" onclick="setLocation('<?php echo $this->getAddNewUrl() ?>')">
        <span><span><?php echo $this->__('Add New Address') ?></span></span></button>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $_index=0 ?>
    <?php foreach ($this->getAddressCollection() as $_address): ?>
        <?php if($_index%3==0): ?><div class="col3-set"><?php endif; ?>
        <div class="col-<?php echo $_index%3+1; ?>">
                <p class="actions">
                    <a href="<?php echo $this->getEditAddressUrl($_address) ?>">
                    <?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> 
                    <a href="<?php echo $this->getSetAddressUrl($_address) ?>">
                    <strong><?php echo $this->__('Select Address') ?></strong></a>
                </p>
                <address>
                    <?php echo $_address->format('html') ?>
                </address>
                <?php if($this->isAddressDefaultBilling($_address)): ?>
                   <strong><?php echo $this->__('Default Billing') ?></strong>
                <?php endif; ?>
                <?php if($this->isAddressDefaultShipping($_address)): ?>
                    <br /><strong><?php echo $this->__('Default Shipping') ?></strong>
                <?php endif; ?>
        </div>
        <?php $_index++ ?>
        <?php if($_index && $_index%3==0): ?></div><?php endif; ?>
    <?php endforeach; ?>
    <?php if(!$_index || $_index%3!=0): ?></div><?php endif; ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small>
        <?php echo $this->__('Back to Billing Information') ?></a></p>
    </div>
</div>
