<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Get the list of all items from the 'getItem'
 */ 
 $_item = $this->getItem() ?>
<?php 
/**
 *  Get the order item Collection
 */
$_order = $this->getItem()->getOrderItem()->getOrder() ?>
<?php 
/**
 * Get Order Id
 */

?>
<tr class="border invoice_table" id="order-item-row-<?php echo $_item->getId() ?>">
    <td width="30%"><h4 class="product-name"><?php
/**
 * Getting Property name
 */
  echo $this->htmlEscape($_item->getName()) ?></h4>
        <?php if($_options = $this->getItemOptions()): ?>
       <dl class="item-options">
        <?php
            /**
 * Iterating the "$options" Array 
 */     
    foreach ($_options as $_option):
            $seats = 1;
/**
 * Set the value "Accomodate"
 */
            $searchValue = $this->__('Accomodate(s)');
/**
 * Assign the Value to "$resultValue"
 */ 
            $resultValue = $_option['label'];
/**
 * Check weather the Value of "$searchValue" and "$resultValue" are equal
 */
            if($searchValue == $resultValue){
/**
 * Converting the Value to Integer
 */
            $seats = (int) $_option['value'];      
            }
            /**
             * check weather the seats Value is greater than zero 
             */
            if($seats > 0){
            ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?>: </dt>
            <?php 
            /**
             * check weather the get Print Staus is not an empty
             */
            if (!$this->getPrintStatus()): ?>
                <?php
/**
                 * Set the "_formatedOptionValue" value from the method "getFormatedOptionValue"
                 */ 
$_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                    <?php echo $_formatedOptionValue['value'] ?>
                    <?php 
/**
 * Check the "_formatedOptionValue" is set
 */
 if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value"><dl class="item-options"><dt>
                            <?php echo $this->htmlEscape($_option['label']) ?></dt>
                            <dd>
                            <?php echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd> <br>          
            <?php else: ?>
                <dd><?php echo $this->htmlEscape( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) ) ?></dd>               
            <?php endif; ?>
            <?php }  ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php 
        /**
         * check weather the addInfoBlock isset  
         */
        if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $this->htmlEscape($_item->getDescription()) ?>
        <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item->getOrderItem()) && $_item->getGiftMessageId()): ?>
            <a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="gift-message-link" 
            onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')">
            <?php echo $this->__('Gift Message') ?></a>
        <?php endif; ?>
    </td>
    <td>
    <?php echo $this->htmlEscape(Mage::helper('core/string')->splitInjection($this->getSku())) ?>
    </td>
    <td class="a-right">
        <?php 
        /**
         *  Make sure displaySalesPriceExclTax or displaySalesBothPrices is not empty
         */
        if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?><span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price"><?php endif; ?>
                        <span class="label"><?php echo $this->__('Excl. Tax'); ?>:
                        </span>
                    <?php 
                    /**
                     *  Make sure  the Weee Tax Applied Amount and typeofDisplay value is not null
                     */
                     if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span><?php endif; ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span  onclick="taxToggle('eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total">
                <?php else: ?>
                    <span class="cart-price"><?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()+$this->getItem()->getWeeeTaxAppliedAmount()+$this->getItem()->getWeeeTaxDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
                    <?php endif; ?></span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span id="eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>" class="cart-tax-info"  style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small><?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <?php echo $tax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($tax['amount']); ?>
                                </span>
                            <?php endforeach; ?></small>
                        <?php }
                        /**
                         *  Make sure displaySalesPriceExclTax or displaySalesBothPrices is not empty
                         */
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <?php 
                            /**
                             * Iterating Loop
                             */
                            
                            foreach (Mage::helper('weee')->getApplied($this->getItem()) as $getTax): ?>
                                <span class="nobr">
                                <small>
                                <?php echo $getTax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($getTax['amount_incl_tax']); ?></small>
                                </span>
                            <?php endforeach; ?>
                        <?php }
                        /**
                         * Make sure displaySalesPriceExclTax or displaySalesBothPrices is not empty
                         */
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small>
                            <?php 
                            /**
                             * Iterating loop
                             */
                            
                            foreach (Mage::helper('weee')->getApplied($this->getItem()) as $taxValue): ?>
                                <span class="nobr"><?php echo $taxValue['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($taxValue['amount_incl_tax']); ?>
                                </span>
                            <?php endforeach; ?>
                            </small>
                        <?php } ?>
                    </span>

                    <?php 
                    /**
                     * Make sure displaySalesPriceExclTax or displaySalesBothPrices is not empty
                     */
                    if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> 
                            <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()+$this->getItem()->getWeeeTaxAppliedAmount()+$this->getItem()->getWeeeTaxDisposition()); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br />
        <?php endif; ?>
        <?php 
                  /**
                   * Make sure displaySalesBothPrices or displaySalesPriceInclTax is not empty
                   */
        if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?> <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                   <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?> <span class="label">
                       <?php echo $this->__('Incl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?> </span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($_incl+$this->getItem()->getWeeeTaxAppliedAmount()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($_incl-$this->getItem()->getWeeeTaxDisposition()) ?>
                    <?php endif; ?>

                </span>


                <?php 
                if (Mage::helper('weee')->getApplied($this->getItem())): ?>
                    <span class="cart-tax-info" id="unit-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small><?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($tax['amount']); ?>
                                </span><?php endforeach; ?></small>
                        <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                            <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?>
                                </span><?php endforeach; ?></small>
                        <?php } ?></span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span  onclick="taxToggle('unit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total">
                            <span class="nobr">
                            <?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                            <br /> 
                            <?php echo $this->getOrder()->formatPrice($_incl+$this->getItem()->getWeeeTaxAppliedAmount()); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </td>
    
    <?php 
    /**
     *  Getting Qty
     */
    ?>
    <td class="a-center"><?php echo $_item->getQty()*1 ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax"><?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price"><?php endif; ?>
                        <span class="label">
                        <?php echo $this->__('Excl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span><?php endif; ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span  onclick="taxToggle('esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');" class="cart-tax-total">
                <?php else: ?>
                    <span class="cart-price"><?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()+$this->getItem()->getWeeeTaxAppliedRowAmount()+$this->getItem()->getWeeeTaxRowDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
                    <?php endif; ?></span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $taxAmt): ?>
                                <span class="nobr"><?php echo $taxAmt['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($taxAmt['row_amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $taxVal): ?><span class="nobr">
                                <small><?php echo $taxVal['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($taxVal['row_amount_incl_tax']); ?>
                                </small>
                                </span>
                            <?php endforeach; ?>
                        <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <?php echo $tax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?>
                                </span>
                            <?php endforeach; ?></small>
                            <?php } ?></span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> 
                            <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()+$this->getItem()->getWeeeTaxAppliedRowAmount()+$this->getItem()->getWeeeTaxRowDisposition()); ?></span>
                        </span><?php endif; ?>
                <?php endif; ?></span>
            <br /><?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                   <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price"><?php endif; ?>
                        <span class="label">
                        <?php echo $this->__('Incl. Tax'); ?>:
                    </span><?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    </span><?php endif; ?>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($_incl+$this->getItem()->getWeeeTaxAppliedRowAmount()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($_incl-$this->getItem()->getWeeeTaxRowDisposition()) ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?> <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $taxAmount): ?><span class="nobr">
                                <?php echo $taxAmount['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($taxAmount['row_amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $itemTax): ?>
                                <span class="nobr"><small>
                                <?php echo $itemTax['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($itemTax['row_amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                        <?php }
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $taxPrice): ?>
                                <span class="nobr">
                                <?php echo $taxPrice['title']; ?>: 
                                <?php echo $this->getOrder()->formatPrice($taxPrice['row_amount_incl_tax']); ?>
                                </span>
                            <?php endforeach; ?>
                            </small>
                        <?php } ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br />
                             <?php echo $this->getOrder()->formatPrice($_incl+$this->getItem()->getWeeeTaxAppliedRowAmount()); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>



            </span>
        <?php endif; ?>
    </td>
    <td class="a-right"><?php echo $_order->formatPrice(-$_item->getDiscountAmount()) ?></td>
    <td class="last a-right">
        <?php echo $_order->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount()+$_item->getWeeeTaxAppliedRowAmount()) ?>
    </td>
</tr>
