<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php


$_order = $this->getOrder ();
/**
 * Getting Order Collection
 */
$items = $_order->getItemsCollection ();

/**
 * Iteration Loop
 */
foreach ( $items as $item ) {
	$orderId = $item ['order_id'];
	/**
	 * Getting Product Options
	 */
	$details = unserialize ( $item ['product_options'] );
	/**
	 * Iteration Loop
	 */
	foreach ( $details as $det ) {
		/**
		 * Get the Value of ServiceFee
		 */
		$securityFee = $det ['securityFee'];
		$productId = $det ['product'];
		/**
		 * Get the Value of ServiceFee
		 */
		$serviceFee = $det ['serviceFee'];
	}
}

/**
 * For whether checking hourly based or not
 */
$hourlyFlag = Mage::helper ( 'airhotels/airhotel' )->hourlyFlag ( $_order );
$getSecurityEnabledOrNot = Mage::helper ( 'airhotels/product' )->getSecurityEnabledOrNot ();
$product = Mage::getModel ( 'catalog/product' )->load ( $productId );
?>
<!--  invoice starts -->
<h1><?php echo $this->__('Booking #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Booking Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php $_invoice = $this->getInvoice()?>
<?php if($_invoice): ?>
    <?php $_invoices = array($_invoice); ?>
<?php else: ?>
    <?php $_invoices = $_order->getInvoiceCollection()?>
<?php endif; ?>
<?php foreach ($_invoices as $_invoice): ?>
<h2 class="h2"><?php echo $this->__('Invoice #%s', $_invoice->getIncrementId()) ?></h2>
<div class="col2-set">
	<div class="col-1">
        <?php if (!$_order->getIsVirtual()): ?>
            <h3><?php echo $this->__('Shipping Address') ?></h3>
            <?php $_shipping = $_invoice->getShippingAddress()?>
            <address><?php echo $_shipping->format('html') ?></address>
	</div>
	<div class="col-2">
        <?php endif; ?>
            <h3><?php echo $this->__('Billing Address')?>
            </h3>
            <?php $_billing = $_invoice->getbillingAddress()?>
            <address>
            <?php echo $_order->getBillingAddress()->format('html')?>
            </address>
	</div>
	<!--  check wether the IsVirtual -->
        <?php if (!$_order->getIsVirtual()): ?>
    </div>
<div class="col2-set">
	<div class="col-1">
		<h3>
            <?php echo $this->__('Shipping Method')?>
            </h3><?php echo $_order->getShippingDescription()?>
        </div>
        <?php endif; ?>
        <div class="col-2">
		<h3>
            <?php echo $this->__('Payment Method')?>
            </h3><?php echo $this->getPaymentInfoHtml() ?></div>
</div>
<h3>
    <?php echo $this->__('Property Invoiced') ?></h3>
<table class="data-table"
	id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<thead>
		<!-- Printing the ProductName,SKU,Price -->
		<tr>
			<th>
                <?php echo $this->__('Product Name')?>
                </th>
			<th>
                <?php echo $this->__('SKU')?>
                </th>
			<th class="a-right">
                <?php echo $this->__('Price') ?></th>
			<th class="a-center"><span class="nobr"><?php
	
if ($hourlyFlag == 0) {
		echo $this->__ ( 'No. of day(s) Invoiced' );
	} else {
		echo $this->__ ( 'No. of hour(s) Invoiced' );
	}
	?></span></th>
			<th class="a-right"><?php echo $this->__('Subtotal') ?></th>
		</tr>
	</thead>
	<tfoot>
		<!-- get invoice total Value  -->   
            <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
        </tfoot>
        <?php $_items = $_invoice->getItemsCollection(); ?>
        <?php $_count = $_items->count(); ?>
        <?php
	
foreach ( $_items as $_item ) :
		if ($_item->getOrderItem ()->getParentItem ()) {
			continue;
		}
		?>
        <tbody><?php  echo $this->getItemHtml($_item)?>
        </tbody><?php
	
endforeach;
	$order = Mage::getResourceModel ( 'sales/order_collection' )->addFieldToFilter ( 'entity_id', $orderId );
	foreach ( $order as $orderVal ) {
		$orderCurrencyCode = $orderVal ['order_currency_code'];
	}
	$orderCurrencySymbol = Mage::app ()->getLocale ()->currency ( $orderCurrencyCode )->getSymbol ();
	?>		
        </table>
<script type="text/javascript">decorateTable('my-invoice-table-<?php echo $_invoice->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php endforeach; ?>

<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript">window.print();</script>



<script type="text/javascript">		
var $jq = jQuery.noConflict(); 		

function securityFee(){	
<?php

if ($getSecurityEnabledOrNot == 0 || $securityFee == 0) {
	$allOptions = $product->getOptions ();
	if ($allOptions) {
		foreach ( $allOptions as $option ) {
			foreach ( $option->getValues () as $key => $value ) {
				?>
			
		$jq('.subtotal').after('<tr class="invoice_<?php echo strtolower($value->getDefaultTitle ()); ?>_fee"><td colspan="4" class="a-right"><?php echo $this->__($value->getDefaultTitle ().' Fee'); ?></td><td class="last a-right"><span class="price"><?php echo $orderCurrencySymbol.  number_format((float)$value->getPrice (), 2, '.', '');?></span></td></tr>');
		<?php
			}
		}
	}
}

?>	
	$jq('.subtotal').after('<tr class="invoice_processing_fee"><td colspan="4" class="a-right">Processing Fee</td><td class="last a-right"><span class="price"><?php echo $orderCurrencySymbol.  number_format((float)$serviceFee, 2, '.', '');?></span></td></tr>');		
}

$jq( document ).ready(function() {
	securityFee();
});				
</script>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']}) window.print(); </script>
<!--  invoice ends -->
