<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$format = Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM);
?>
<div class="my-account" style="padding:0">
	<h1 class="dashboard_leftside_heading"><?php echo $this->__('Current Trip');?></h1>
    <div  id="current_div" class="main_content">
    	<?php $current_value = Mage::getModel('airhotels/property')->currentTrip();?>
        <div class="property_history_responsivetable">
        	<table cellspacing="2" cellpadding="2" id="property_trip_table">
            	<thead>
                	<tr>
	                    <th width="10%"><?php echo $this->__('S.No'); ?></th>
	                    <th width="20%"><?php echo $this->__('Image'); ?></th>
	                    <th width="35%"><?php echo $this->__('Experience Name'); ?></th>
	                    <th width="20%"><?php echo $this->__('Start On'); ?></th>
	                    <th width="15%"><?php echo $this->__('End On'); ?></th>
                     </tr>
                </thead>
                <?php
                $serialNumber = 1;
                $tempValue = 0;
                for ($i = 0; $i < count($current_value[0]); $i++) {
	                $propertyCollection = Mage::getModel('airhotels/property')->getpropertycollection()
	                					->addFieldToFilter(array(array('attribute' => 'entity_id', 'eq' => $current_value[0][$i])));
                    foreach ($propertyCollection as $property) {
	                    $startOn 		= $current_value[1][$i];
	                    $endOn 			= $current_value[2][$i];
	                    $tempValue		= 1;
	                    $thumbGallery 	= $this->helper('catalog/image')->init($property, 'thumbnail', $property->getImage())
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(80, null); ?>
                        <p><?php
                        echo '<tr>';
                        echo '<td width="10%">' . $serialNumber . '</td>'; ?>
                        <td width="20%" style="line-height: 0"> <img src="<?php echo  $thumbGallery ?>" style="width: 50px !important; height: 50px !important;border:2px solid #D4D4D5" /> </td>
                        <?php echo '<td width="35%">' . $property->getName() . '</td>';
                        echo '<td width="20%">' . date('M d, Y h:i A',strtotime($startOn)). '</td>';
                        echo '<td width="15%">' . date('M d, Y h:i A',strtotime($endOn)). '</td>';
                        echo '</tr>';
                        $serialNumber++;
                        ?>
                        </p>
                   	<?php } ?> 
                <?php } ?>
 			</table>
            <?php if(empty($tempValue)) { ?><p  class="nocontent_available"  style="padding:20px 0;"><?php echo $this->__('You have no trips'); ?></p> <?php } ?>
		</div>
	</div>
</div>