<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$baseUrl 	= $this->getBaseUrl();
$skinUrl	= $this->getSkinUrl();
$hostId 	= Mage::getSingleton('customer/session')->getId();
$host 		= Mage::getSingleton('customer/session')->getCustomer();
$hostFirstName = $host->getFirstname(); // First Name
?>
<?php if(( int ) Mage::helper ( 'airhotels/invitefriends' )->getInviteFriendsEnabledOrNot () == 0){?>
<div class="dashboard_invite">
	<div class="dashinvite_section">
        <ul class="clearfix dashboard_invite_list">
	        <li><h4><?php echo $this->__('Invite Friends, earn travel credit'); ?></h4><p><?php echo $this->__('Lorem Ipsum is simply dummy text of the printing and typesetting industry.'); ?></p></li>
	  		<li class="invite_button_list"><a class="import_button" href="<?php echo $this->getBaseUrl();?>airhotels/invitefriends/invite"><?php echo $this->__('Invite Friends');?></a></li>  		
  		</ul>
    </div>
</div>
<?php } ?>