<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */ 
?>

<div class="my-account clearfix">
<div class="page-title">
    <h1 class="dashboard_leftside_heading"><?php echo $this->__('Sent Items'); ?></h1>
</div>
<?php
/** 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$model = Mage::getModel('airhotels/airhotels');
/**
 *Get the Colletion of OutBox Details
 */
$outboxDetailsData = Mage::getModel('airhotels/calendar')->getOutboxDetails();
/**
 *  Make sure the outboxDetailsData Value is Greater than one
 */
if(count($outboxDetailsData) >= 1){
    ?>
    <form name="mailform" action="" method="post">
	    <div id="inboxSpace">
            <div class="innerpage_btn left delete" style="line-height: 26px;margin-left: 10px;" onclick="confirmDelete()"  ><?php echo $this->__('Delete'); ?></div>
            <div class="innerpage_btn left" style="line-height: 26px;margin-left: 10px;">
	       		<input type="button" value="<?php echo Mage::helper('airhotels')->__('Check All'); ?>" onClick="this.value=checkUncheckAll()"/>
	        </div>
	        <table class="inboxTable" >
	            <?php 
	            /**
	             * Iterating the outboxDetailsData
	             */
	            foreach($outboxDetailsData as $outboxDetails){ 
					 $productId = $outboxDetails["product_id"]; 
					 $receiver_id = $outboxDetails["receiver_id"];
				?>
	            <tr style="cursor: pointer" class="read" >
	                <td><input type="checkbox" style="margin-left: 5px" name="messageid[]" value="<?php echo $outboxDetails["message_id"]; ?>"/></td>
	                <td onclick="openMessage(1,'<?php echo $outboxDetails["message_id"]; ?>')">
	                    <?php echo $this->__('To'); ?> : 
	                    <?php
	                    	$customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
	                    	/**
	                     	* Load the customer mail based on id
	                     	*/
	                      	$customer = Mage::getModel('customer/customer')->load($outboxDetails["sender_id"]); 	
	                      	$obj = Mage::getModel('catalog/product');
	                      	$_product = $obj->load($productId);	                      
	                      	$hostId	= $_product->getUserid();
	                      	$host	=  Mage::getModel('customer/customer')->load($hostId);	                      
	                      	if ($customer_id != $receiver_id) {
	                      		echo ucfirst($host->getName());
	                      	}else{
	                      		echo ucfirst($customer->getName());
	                     	}
	                       ?>
	                </td>
	                <td onclick="openMessage(1,'<?php echo $outboxDetails["message_id"]; ?>')">
	                    <?php echo (strlen($outboxDetails["message"])>30)? substr($outboxDetails["message"],0,30) : $outboxDetails["message"]."..";   ?>
	                </td>
	                <td onclick="openMessage(1,'<?php echo $outboxDetails["message_id"]; ?>')">                   
	                    <?php echo date("d/m/Y",strtotime ($outboxDetails["created_date"]));  ?>
	                </td>
	            </tr>
	            <?php  } ?>
	        </table>
	    </div>
    </form>
    <div id="mailSpace" style="display: none">
        
    </div>
        <?php
} else{ ?>
    <h1 class="no_mails">
    <?php echo $this->__('No mail sent'); ?>
    </h1>
    <?php
}
?>
</div>
<script type="text/javascript">
var jQ = jQuery.noConflict();
function openMessage(flag,messageId){
    if(flag==1){
        document.getElementById("inboxSpace").style.display = "none"; document.getElementById("mailSpace").style.display = "block";
        getMessageDetails(messageId);
    }
    else{
        document.getElementById("inboxSpace").style.display = "block"; document.getElementById("mailSpace").style.display = "none";
    }
}
function getMessageDetails(messageId){
    var xmlhttp = getHttp();
    document.getElementById("mailSpace").innerHTML="<div class='loadingWrapper'><div class='content three-bounce'><div class='one'></div><div class='two'></div><div class='three'></div></div></div>";
    xmlhttp.onreadystatechange=function(){
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        { document.getElementById("mailSpace").innerHTML=xmlhttp.responseText; }
    }
    var url = "<?php echo Mage::getBaseUrl() . 'property/property/showmessage/' ?>";
    url=url+"id/"+messageId+"/show/out";xmlhttp.open("GET",url,true);xmlhttp.send();
}
function getHttp(){
    var xmlhttp;
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
    return xmlhttp;
}
function confirmDelete(){
    
    if(jQ("input:checked").length != ""){
    if(confirm("<?php echo $this->__('Are you sure want to delete'); ?>")){
    document.mailform.submit();
        return true;
    }
    }
    else{
        confirm("<?php echo $this->__('Please select the checkbox to delete'); ?>"); 
        return false;
    }
}
        var checkAllInboxCheckboxes = 0;
        function checkUncheckAll() {
        if(checkAllInboxCheckboxes == 0){   
        jQ('#inboxSpace input:checkbox').attr('checked', 'checked');
        checkAllInboxCheckboxes = 1;
        return "<?php echo Mage::helper('airhotels')->__('Uncheck All'); ?>";
        }else{  
        jQ('#inboxSpace input:checkbox').removeAttr('checked', 'checked');
        checkAllInboxCheckboxes = 0;
        return "<?php echo Mage::helper('airhotels')->__('Check All'); ?>";
        }
        }
</script>