<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */ 
?>
<ul>
    <?php
    $count = 1;
    $threeDiv = 1;
    /**
 	* create the Model 
    */
    $model = Mage::getModel('catalog/product');
    /**
 	* call the getPropertyTimeLabelByOptionId method
    */
    $propertyTimeData = $propertyTimeId = Mage::helper('airhotels/airhotel')->getPropertyTimeLabelByOptionId();
	/**
	 * get the RateColletion
	 */
    $rateCollection = Mage::getModel('airhotels/property')->getPopularProperty();
    /**
 	* Currency Sybmol Value.
    */
    $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
    /**
    * Check the value of $rateCollection
    */
   if(count($rateCollection)!= ''){
	/**
	* Iterating the loop
	*/
   foreach ($rateCollection as $key => $id) {
	/**
	 * Get the Prodyuct Colletion based on the ID
	 */
   $product = $model->load($id);
   /**
 	* Get the Customer Data
    */
    $customerData = Mage::getModel('airhotels/product')->getCustomerPictureById($product->getUserid());
    /**
 	* Laod the Customer Info.
    */
    $customer = Mage::getModel('customer/customer')->load($product->getUserid());
    	if ($threeDiv <= 3) { ?>
            <li class="home-small-dealbox<?php echo $threeDiv ?> res_list">
                <div id="popular-wishlist" class="clearfix popular-wishlist">
                    <div class="row-wishlists-list clearfix">
                        <div class="wishlists-list-item space_list">
                        <?php                         
                        /**
                         * Getting Image
                         */                        
                        ?>
                        <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" class="matte-media-box" >
                        	<img src="<?php echo $this->getPopularImage($product); ?>" 
                            width ="250px" height="149px" title="<?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?>"/>
                        </a>
                  			<div class="feed_item_device_view">
			                    <div class="floatleft">
			                        <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" >
			                            <span class="h4"><?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?>
			                            </span>
			                        <span><?php echo $product->getState().','. $product->getCountry(); ?></span></a>
			                    </div>
			                    <div class="popular_price">
			                        <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" >
			                        <span class="price-tag-price">
			                        <?php echo $currencySymbol . round(Mage::helper('directory')->currencyConvert($product->getPrice(), Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0); ?>
			                        </span>
			                         <?php
			                         /**
			  						  * Property Time 
			                          */
			                         $propertyTime = $product->getPropertyTime();     
			                         /**
			  						  * Hourly Enabled or Not Vlaue.
			                          */                              
			                         $hourlyEnabledOrNot = Mage::helper('airhotels/product')->getHourlyEnabledOrNot();  
			                        echo $this->getPopularStyle($propertyTime,$propertyTimeData,$hourlyEnabledOrNot); ?>
			                        </a>
			                    </div>
                			</div>
                            <div class="info_card clearfix">
                                <div class="floatleft">
                                    <a href="<?php echo Mage::helper('airhotels/product')->getprofilepage().'id/'.$product->getUserid();?>" class="matte-media-box-small">
                                        <?php if (!empty($customerData[0]["imagename"])): ?>   
                                            <img src="<?php echo Mage::getBaseUrl('media') . "catalog/customer/thumbs/" . $customerData[0]["imagename"] ?>" height="38"alt="" title=""/>
        								<?php else: ?> 
                                            <img src="<?php echo $this->getSkinUrl('images/no_user.jpg'); ?>"  height="38" alt="" title=""/> <?php endif; ?>
                                    </a>
                                </div>                                
                                <div class="span1">
                                    <h4><a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" style="text-decoration: none;">
                                    <?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?></a></h4>
                                    <p><a style="text-decoration: none;" href="<?php echo Mage::helper('airhotels/product')->getprofilepage().'id/'.$product->getUserid();?>">
                                    <?php echo $customer->getName(); ?></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <?php
            /**
             * Check the value of '$threeDiv'
             */
            if ($threeDiv == 3) {
                echo '<div class="clear"></div>';
                $twoDiv = 1;
            }
            $threeDiv = $threeDiv + 1;
        } else {
			if ($twoDiv <= 2) { ?>
                <li class="home-medium-dealbox<?php echo $twoDiv ?>">
                    <div class="popular_2up_listings_view">
                        <div class="row2-wishlists-list clearfix">
                            <div class="wishlists2-list-item twospace_list">
                                <a class="matte2-media-box" href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" >
                                    <img src="<?php
            if ($product->getImage() != 'no_selection') {
                echo Mage::getBaseUrl('media') . 'catalog/product/' . $product->getImage();
            } else {
                echo $product->getImageUrl();
            }
            ?>" 
            alt="<?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?>" 
            width ="460px" height="255px" 
            title="<?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?>"/></a>
                                 <div class="feed_item_view">
                                        <div class="floatleft">
                                            <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>">
                                                <span class="h4">
                                                <?php echo Mage::helper('airhotels/property')->getPropertyName($product->getName()); ?></span>
                                            <span>
                                            <?php echo $product->getState() . ',' . $product->getCountry(); ?></span>
                                            </a>
                                        </div>
                                        <div class="popular_price">
                                            <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>">
                                                <span class="price-tag-price">
            								<?php echo $currencySymbol . round(Mage::helper('directory')->currencyConvert($product->getPrice(), Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0); ?>
                                            </span>
                                                  <?php $propertyTime = $product->getPropertyTime();        
					                         $hourlyEnabledOrNot = Mage::helper('airhotels/product')->getHourlyEnabledOrNot(); 
					                         echo $this->getPopularStyle($propertyTime,$propertyTimeData,$hourlyEnabledOrNot);
					                         ?>
                                            </a> 
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </li>
                <?php
                if ($twoDiv == 2) {
                    echo '<div class="clear"></div>';
                    $threeDiv = 1;
                }
                $twoDiv = $twoDiv + 1;
            }
        }
        if ($count == 10) {
            break;
        }
        $count = $count + 1;
    }
   }else{
      echo '<div class="emty_grid" style="height: 221px;">'. $this->__('No Records!').'</div>';
   }
    ?>
</ul>