<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Get the Customer id 
 */
$customerid  = Mage::app()->getRequest()->getParam('id');
/**
 * Load the Customer id and get the customer info.
 */
$customer = $address = Mage::getModel('customer/customer')->load($customerid);
/**
 * load the customer id and get the Profile Photo
 */
$profilePhoto = Mage::getModel('airhotels/product')->getCustomerPictureById($customerid);
/**
 * GET THE Customer name.
 */
$customerName = $customer->getName();
?>
<div id="room">
    <div class="middle" id="profile_blog">
        <div class="profile_pic clearfix">
            <div class="_pm_container">
                <div class="_pm_shadow r"></div>
                <div class="_pm_shadow l"></div>
                <div class="_pm clearfix">
                    <div class="_pm_inner clearfix">
                     <?php
                     /**
                      * Check weather the value 
                      */ 
                     if(!empty($profilePhoto[0]["imagename"])){                     
                     	echo "<img class='profilephoto' src='" . Mage::getBaseUrl('media') . "catalog/customer/" . $profilePhoto[0]["imagename"] . "' /> ";
                     }else{
                         echo "<img class='profilephoto' src='".$this->getSkinUrl('images/no_user.jpg')."' /> ";
                     }
                     ?>
                    </div>
                </div>
            </div>
        </div>
        <h2><?php echo $customerName; ?></h2>
        <b><strong></strong></b>
    </div>
    <div class="clear"></div>
</div>