<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Get the Customer ID Value.
 */
$customerid = Mage::app()->getRequest()->getParam('id');
/**
 * Get Currency Sybmol Value.
 */
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
/**
 * get the Property Colletion with filers
 * Filter by 'status' and 'property approved' and 'userid'
 */
$PropertyCollection = Mage::getModel('airhotels/property')
        			->getpropertycollection()
        			->addAttributeToSelect('*')
        			->addAttributeToFilter('status', array('eq' => 1))
        			->addAttributeToFilter('propertyapproved', array('eq' => 1))
        			->addAttributeToFilter('userid', array('eq' => $customerid));
/**
* Proeprty Time Data.
*/
$propertyTimeData  = Mage::helper('airhotels/airhotel')->getPropertyTimeLabelByOptionId();
?>
<div id="profile_gridlist">
    <div class="usergridlist">
        <h1 class="arrowbubble"> <b class="profilelist_id icon_grid"></b> <?php echo $this->__('My Listing') ?></h1>
      	<div id="scroll-listing">      
        <?php
        /**
 		 * $propertyCollectionCount vlaue.
         */
        $propertyCollectionCount = count($PropertyCollection);
        /**
         * Make sure the $propertyCollectionCount has greater the value.
         */
        if($propertyCollectionCount >= 1){
        	foreach ($PropertyCollection as $property) {
				/**
				 * get the Product Name.
				 */
	            $productName = $property->getName();
	            /**
	 			 * get the Product url
	             */
	            $productUrl = $property->getProductUrl();
				/**
				 * Get the Product Price Vlaue.
				 */
	            $productPrice = $currencySymbol . round(Mage::helper('directory')->currencyConvert($property->getPrice(), Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0);
	            /**
	    	     * get the Product Image 
	             */
	            $productImage = $this->helper('catalog/image')->init($property, 'image')->resize(150, 150);
	            ?>
	            <div class="rowList">
	                <a href="<?php echo $productUrl ;?>">
	                <img src="<?php echo $productImage; ?>" width="91" height="62" alt="<?php echo $productName; ?>"  class="floatleft"/></a>
	                <div class="related_listing_desc left">
	                   <a href="<?php echo $productUrl ;?>" style="text-decoration: none;"> 
	                   <strong><?php echo $productName; ?></strong></a>
	                   <span><?php echo $productPrice; ?> <?php                 
						/**
						 * Property TIme Vlaue.
						 */
	                    $propertyTime = $property->getPropertyTime();   
	                    /**
	 					 * Get the Hourly ENabledVlaue.
	                     */                
	                    $hourlyEnabledOrNot = Mage::helper('airhotels/product')->getHourlyEnabledOrNot();  
	                    /**
	                     * make sure the $propertyTime and $propertyTimeData ,$hourlyEnabledOrNot are set
	                     */
	                    if ($propertyTime == $propertyTimeData && $hourlyEnabledOrNot == 0) {                 
	                    	echo $this->__('Per Hour');    
	                    }else{
	                    	echo $this->__('Per Night'); 
	                    } ?>                           
	                    </span>
	                </div>
	            </div>
	            <?php
        	}
		}else{ ?>
        	<p class="list_text_center"><?php echo $this->__('No listings available') ?></p>
       <?php } ?>
       </div>
    </div>
</div>