<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="page-title" style="margin:0">
        <h1 class="dashboard_leftside_heading"><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="newsletter_container" style="border-bottom:none;padding:10px;">
        <?php echo $this->getBlockHtml('formkey')?>
       <!--  <h2 class="legend"><?php //echo $this->__('Newsletter Subscription') ?></h2> -->
        <ul class="form-list">
            <li class="control general_subs">
            <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label style="font-size:13px;" for="subscription" class="generalsubscription"><i class="sprimg"></i><?php echo $this->__('General Subscription') ?></label></li>
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
        </ul>
    </div>
  
     <div class="buttons-set" style="clear: both;margin:0;padding:0 10px 10px;border-top: none!important;text-align: right;border: 1px solid #ccc;background-color: #fff;">
        <a style="float:left" class="import_button" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('<< Back') ?></a>
        <button type="submit" title="<?php echo $this->__('Save Address') ?>" class="import_button"><?php echo $this->__('Save') ?></button>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
