<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 
/**
 * Mustishipping state
 * 
 * @see Mage_Checkout_Block_Multishipping_State
 */
?>
<!-- checkout progress state for order  -->
<ul class="checkout-progress" id="checkout-progress-state">
<?php 
/**
 * Iterating loop
 */

foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"
    <?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>>
    <span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach; ?>
</ul>
<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
