<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     0.2.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Get the hourly Product id
 */
$productId = Mage::getSingleton('core/session')->getHourlyProductId();
/**
 * For hourly wise property
 */  
$propertyTime = Mage::getModel('catalog/product')->load($productId)->getPropertyTime();
/**
 * Get the property time label by option Id
 */
$propertyTimeData = Mage::helper('airhotels/airhotel')->getPropertyTimeLabelByOptionId(); 
?>

<?php $_item = $this->getItem();  ?>
<tr>
    <td><h3 class="product-name"><?php echo $this->htmlEscape($this->getProductName()) ?></h3>
         <h5><?php    
         /**
            Getting Id
          */
                   $subId = Mage::getSingleton('core/session')->getSubId();
                   $subscriptionValue = Mage::getSingleton('core/session')->getsubscriptionValue();
                  if($subId > 0){ echo '('.$subscriptionValue.')'; } ?></h5>
    
       
    </td>
     <?php
        /**
         * Get the options List
         */
        if ($_options = $this->getOptionList()):
        ?>  
            <?php     
            /**
             * Array reversing.
             */       
            $_options = array_reverse($_options);
            /**
             * Iteration for loop
             */
            foreach ($_options as $_option) :
            ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
           <td style="width: 70px; text-align: center;" 
            <?php if (isset($_formatedOptionValue['full_view'])): ?> 
               class="truncated"<?php endif; ?>>
              <?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </td>
            <?php endforeach; ?>
        
        <?php endif;
     /**
      * For hourly based property
      */ 
        
     if($propertyTime == $propertyTimeData) {
     /**
      * Get the hourly Night Fee.
      * Checking property time
      */

     $hourlyNightFee = Mage::getSingleton('core/session')->getHourlyNightFee();   
     /**
      * Overall total Hours
      */    
     $overallTotalHours = Mage::getSingleton('core/session')->getOverallTotalHours();   
     ?>     
     <td class="a-center"><?php if(!empty($overallTotalHours)){ 
     	
     	echo $overallTotalHours; 
     } 
     if(!(empty($hourlyNightFee)) && ($hourlyNightFee >= 1) ) {
     	echo ' <span>['.$this->__('Excluding night hour(s)').']</span>';  
     	  
     }
     ?></td> 
     <?php }else{
        /**
          * Displaying cart items qty
          */
       ?>
      	<td class="a-center"><?php echo $_item->getQty(); ?></td>
      
     <?php } ?> 
      
          <?php 
          /**
           * For hourly based property
           */ 
          if($propertyTime == $propertyTimeData){    

          /**
           * Overall fees 
           */
          $hourlyNightFee = Mage::getSingleton('core/session')->getHourlyNightFee();
          
          /**
           * Check weather the hourly fee is empty
           */
          if(!(empty($hourlyNightFee)) && ($hourlyNightFee >=1 )){

          /**
           * get the property overnight fee
           */
          $propertyOverNightFee = Mage::helper('airhotels/airhotel')->getPropertyOverNightFeeByProductId($productId);                        
          ?> 
          <td class="a-center"><?php if(!empty($propertyOverNightFee)){ 
          echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol().$propertyOverNightFee; 
          } ?></td>
          <?php }
         }?>
            
            
        <?php
        /**
         * Get the Product Additional Information Block
         */ 
        if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?><span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            <?php endif; ?>
        </span>


        <?php
        /**
         * Calculating the tax Values 
         * If the price is not empty, goes to product price
         */
         if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" style="display:none;" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" >
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?><small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?><span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?>
                        </span>
                        <br /><?php endforeach; ?>
                        </small>
                <?php }
                /**
                 * Make sure the Product is applying any tax 
                 */
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?><span class="nobr">
                    <small>
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small>
                        </span><br /><?php endforeach; ?>
                <?php }
                /**
                 * Make the Sales Value between tax and applied Amount
                 */
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <br />
                    <?php endforeach; ?>
                    </small>
                <?php } ?></div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price"><?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): 
                 echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); 
             else: 
                 echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ;
             endif;  ?></span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div style="display:none;" class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" >
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small><?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?>
                        </span><br /><?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <small><?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php }if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small><?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <br /><?php endforeach; ?> </small>
                <?php } ?></div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>       
          
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>

        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div  id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;" class="cart-tax-info"><small>
                 <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                    <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?>
                        </span>
                        <br />
                        <?php endforeach; ?></small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small>
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small><?php } ?></div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
            <?php endif; ?>

        </span>


        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div  id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;" class="cart-tax-info">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?><span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?>
                        </span>
                        <br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small>
                        <?php echo $tax['title']; ?>:
                         <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?>
                         </small></span>
                         <br /><?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?>
                        </span><br />
                    <?php endforeach; ?>
                    </small><?php } ?></div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>